name: getx_starter_project
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2

  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.1.5

  ease: ^0.0.10

  dio: ^4.0.6
  dio_cache_interceptor: any
  dio_logger: ^4.0.8+8

  cached_network_image: ^3.2.0
  get: 4.6.1
  flutter:
    sdk: flutter

flutter_assets:
  assets_path: assets/
  output_path: lib/core/resourses/
  filename: assets.dart
flutter_icons:
  android: launcher_icon
  ios: true
  remove_alpha_ios: true
  image_path: assets/images/logo.png
  flutter: null

dev_dependencies:
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
